version: "3.7"
services:
  mozzy:
    build:
      context: .
      args:
        user: "$USER"
    container_name: mozzy_container
    network_mode: "host"
    volumes:
    - type: bind
      source: ./
      target: /home/${USER}/dev
    command: "tail -f /dev/null"
